--- 
abstract: A Catalyst & DBIx::Class powered Wiki.
author: Marcus Ramberg C<marcus@thefeed.no>
build_requires: 
  Test::WWW::Mechanize::Catalyst: 0
  WWW::Mechanize::TreeBuilder: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MojoMojo
no_index: 
  directory: 
    - inc
    - t
requires: 
  Algorithm::Diff: 1.1901
  Archive::Zip: 1.14
  Catalyst: 5.7000
  Catalyst::Action::RenderView: 0.07
  Catalyst::Controller::BindLex: 0
  Catalyst::Controller::HTML::FormFu: 0
  Catalyst::Model::DBIC::Schema: 0.01
  Catalyst::Model::Search: 0
  Catalyst::Plugin::Authentication: 0.07
  Catalyst::Plugin::Authentication::Store::DBIC: 0
  Catalyst::Plugin::Cache::FileCache: 0
  Catalyst::Plugin::ConfigLoader: 0.13
  Catalyst::Plugin::Email: 0
  Catalyst::Plugin::FillInForm: 0.04
  Catalyst::Plugin::FormValidator: 0.02
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::Singleton: 0.02
  Catalyst::Plugin::Static::Simple: 0.07
  Catalyst::Plugin::SubRequest: 0.09
  Catalyst::Plugin::Unicode: 0.1
  Catalyst::Plugin::UploadProgress: 0
  Catalyst::View::TT: 0.23
  Config::General: 0
  DBD::SQLite: 1.08
  DBIx::Class: 0.08
  DBIx::Class::DateTime::Epoch: 0
  DBIx::Class::HTML::FormFu: 0
  Data::FormValidator::Constraints::DateTime: 0
  Data::Page: 2.00
  DateTime: 0.28
  DateTime::Format::Mail: 0
  File::MMagic: 1.27
  HTML::Prototype::Useful: 0.01
  HTML::Scrubber: 0
  HTML::Strip: 1.04
  HTML::TagCloud: 0
  IO::Scalar: 0
  Image::ExifTool: 0
  Image::Math::Constrain: 0
  Imager: 0
  LWP::Simple: 0
  Module::Pluggable::Ordered: 1.4
  Moose: 0
  Pod::Simple::HTML: 3.01
  String::Diff: 0
  Template::Plugin::JavaScript: 0
  Text::Context: 3.5
  URI: 1.35
  URI::Fetch: 0
  XML::Clean: 0
  YAML: 0.36
tests: t/01app.t t/02pod.t t/03podcoverage.t t/formatter_comment.t t/formatter_irclog.t t/formatter_wiki.t t/schema_DBIC.t t/schema_DBIC_Attachment.t t/schema_DBIC_Content.t t/schema_DBIC_Page.t t/schema_DBIC_Person.t t/schema_DBIC_Tag.t t/c/attachment.t t/c/comment.t t/c/journal.t t/c/jsrpc.t t/c/page.t t/c/page_edit.t t/c/user.t
version: 0.999007
